#!/bin/sh

export AUTH_PASSWORD=pannekoek

export SCRY_ENDPOINT=http://localhost:4002
export SCRY_SECRET=oompaloompadoompadeedo

setup() {
	mix deps.get
	mix deps.compile
	mix ecto.setup
}

serve() {
	mix phx.server
}

deploy() {
	lift deploy vik
	lift deploy fog
}

publish() {
	mix docs
	lift deploy docs
}

release() {
	mix hex.publish
}
